const Constants = {

    BASE_URL: 'http://127.0.0.1:8000/api',


    ADD_USER_REQUEST: "ADD_USER_REQUEST",
    ADD_USER_SUCESS: "ADD_USER_SUCESS",
    ADD_USER_FAIL: "ADD_USER_FAIL",

    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCESS: "ADD_USER_ADDRESS_SUCESS",
    ADD_USER_ADDRESS_FAIL: "ADD_USER_ADDRESS_FAIL",

}

export default Constants 